CREATE DATABASE etl_county_db;
USE etl_county_db;

DROP TABLE access;

CREATE TABLE access (
ID INT PRIMARY KEY,
FIPS INT,
Year INT,
LACCESS_POP DECIMAL(16,8),
PCT_LACCESS_POP DECIMAL(16,8),
LACCESS_LOWI DECIMAL(16,8),
PCT_LACCESS_LOWI DECIMAL(16,8),
LACCESS_HHNV DECIMAL(16,8),
PCT_LACCESS_HHNV DECIMAL(16,8),
LACCESS_CHILD DECIMAL(16,8),
PCT_LACCESS_CHILD DECIMAL(16,8),
LACCESS_SENIORS DECIMAL(16,8),
PCT_LACCESS_SENIORS DECIMAL(16,8),
LACCESS_WHITE DECIMAL(16,8),
PCT_LACCESS_WHITE DECIMAL(16,8),
LACCESS_BLACK DECIMAL(16,8),
PCT_LACCESS_BLACK DECIMAL(16,8),
LACCESS_HISP DECIMAL(16,8),
PCT_LACCESS_HISP DECIMAL(16,8),
LACCESS_NHASIAN DECIMAL(16,8),
PCT_LACCESS_NHASIAN DECIMAL(16,8),
LACCESS_NHNA DECIMAL(16,8),
PCT_LACCESS_NHNA DECIMAL(16,8),
LACCESS_NHPI DECIMAL(16,8),
PCT_LACCESS_NHPI DECIMAL(16,8),
LACCESS_MULTIR DECIMAL(16,8),
PCT_LACCESS_MULTIR DECIMAL(16,8),
LACCESS_SNAP DECIMAL(16,8),
PCT_LACCESS_SNAP DECIMAL(16,8)

);

SELECT * from access;


