CREATE TABLE access (
  id INT PRIMARY KEY,
LACCESS_POP DECIMAL(8,8),
PCT_LACCESS_POP DECIMAL(8,8),
LACCESS_LOWI DECIMAL(8,8),
PCT_LACCESS_LOWI DECIMAL(8,8),
LACCESS_HHNV DECIMAL(8,8),
PCT_LACCESS_HHNV DECIMAL(8,8),
LACCESS_CHILD DECIMAL(8,8),
PCT_LACCESS_CHILD DECIMAL(8,8),
LACCESS_SENIORS DECIMAL(8,8),
PCT_LACCESS_SENIORS DECIMAL(8,8),
LACCESS_WHITE DECIMAL(8,8),
PCT_LACCESS_WHITE DECIMAL(8,8),
LACCESS_BLACK DECIMAL(8,8),
PCT_LACCESS_BLACK DECIMAL(8,8),
LACCESS_HISP DECIMAL(8,8),
PCT_LACCESS_HISP DECIMAL(8,8),
LACCESS_NHASIAN DECIMAL(8,8),
PCT_LACCESS_NHASIAN DECIMAL(8,8),
LACCESS_NHNA DECIMAL(8,8),
PCT_LACCESS_NHNA DECIMAL(8,8),
LACCESS_NHPI DECIMAL(8,8),
PCT_LACCESS_NHPI DECIMAL(8,8),
LACCESS_MULTIR DECIMAL(8,8),
PCT_LACCESS_MULTIR DECIMAL(8,8)

);

